name: build helper images

env:
  REGISTRY: ghcr.io
  APP_VERSION: 0.0.1
  IMAGE_NAME: ${{ github.repository }}

on:  
  push:
    branches:
      - update-smtp
  workflow_dispatch:

jobs:
  build-push-exim-non-root:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag (from tag or branch)
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            TAG_NAME="${GITHUB_REF#refs/heads/}"
          fi
          echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_ENV
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./kustomize/smtpclient
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-exim:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
